# -*- coding: utf-8 -*-
"""DL_lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1axpHPjTf5scKitKr4Oy8qZWR1kw6Aqna
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import pandas as pd

iris = load_iris()
X, y = iris.data, iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


mlp = MLPClassifier(
    hidden_layer_sizes=(10,10),
    activation='relu',
    solver='adam',
    max_iter=1000,
    random_state=42
)

mlp.fit(X_train, y_train)


y_pred = mlp.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)

report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", report)


disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Class 0", "Class 1", "Class 2"]
)
disp.plot(cmap="Blues")
plt.title("Confusion Matrix")
plt.show()


report_dict = classification_report(
    y_test,
    y_pred,
    target_names=["Class 0", "Class 1", "Class 2"],
    output_dict=True
)

df_report = pd.DataFrame(report_dict).transpose()

plt.figure(figsize=(8,5))
plt.imshow(df_report.iloc[:-1, :-1], cmap="YlGnBu", aspect="auto")

plt.xticks(range(len(df_report.columns[:-1])), df_report.columns[:-1])
plt.yticks(range(len(df_report.index[:-1])), df_report.index[:-1])

for i in range(len(df_report.index[:-1])):
    for j in range(len(df_report.columns[:-1])):
        plt.text(j,
            i,
            f"{df_report.iloc[i, j]:.2f}",
            ha="center",
            va="center",
            color="black"
        )

plt.colorbar(label="Score")
plt.title("Classification Report")
plt.xlabel("Metrics")
plt.ylabel("Classes")
plt.tight_layout()
plt.show()


plt.figure(figsize=(7,5))
plt.plot(mlp.loss_curve_, marker='o')
plt.title("MLP Training Loss Curve")
plt.xlabel("Iterations")
plt.ylabel("Loss")
plt.grid(True)
plt.show()

from sklearn.metrics import precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

metrics = ["Accuracy", "Precision", "Recall", "F1-Score"]
scores = [accuracy, precision, recall, f1]

plt.figure(figsize=(8,5))
bars = plt.bar(metrics, scores,
               color=['pink', 'beige', 'grey', 'red'])

plt.ylim(0, 1.1)
plt.ylabel("Score")
plt.title("MLP Performance Metrics")
plt.grid(axis='y', linestyle='--', alpha=0.6)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2,
             height + 0.02,
             f"{height:.2f}",
             ha='center',
             fontsize=11)

plt.show()

metrics = ['Precision', 'Recall', 'F1-score']

macro = [0.97, 0.96, 0.97]
weighted = [0.97, 0.97, 0.97]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(7,5))

plt.bar(x-width/2, macro, width, label='Macro Avg')
plt.bar(x+width/2, weighted, width, label='Weighted Avg')

plt.xticks(x, metrics)
plt.ylim(0.9,1.0)
plt.ylabel("Score")
plt.title("Macro Average vs Weighted Average")
plt.legend()
plt.grid(axis='y')

plt.show()



